Introduces a system to allow css overrides to be injected from the dashboard config file
gamernetwork/dashi pull request #9
Opened 2018-11-13 09:17 UTC by johnpooch

**Who would you like to review this pull request?**
@currycoder @mrmonkington 

**What does this Pull Request do?**
Adds an optional css class to ticker.html for style overrides. Styling can be written in the dashboard config file (DASHBOARD_STYLE _OVERRIDE). The optional css class in ticker can be used to access the dashboard HTML elements from the config file. So far the option has only been introduced for ticker.html but the same system could be used for all of the HTML templates to allow for increased customisation. 

**How to get started.** 
Get a copy of Dashi working locally. Follow the instructions in the README but instead of copying the example dashboard, copy the lasagne/dashi-configs/network-status.py into dashboards.py (also swap in the network-top-urls.py to ensure the previous dashboard is working as expected). 

Set up a local copy of Mormont https://github.com/gamernetwork/mormont.
I ran some test data using the test-impressions file in Mormont-Client https://github.com/gamernetwork/mormont-client/blob/develop/client/v2/test-impressions.html. This will involve configuring the indexPrefix in Kibana.

2018-11-20 11:43 UTC, currycoder requested changes
Broadly this is looking cool.  I have a few things commented inline, and I'm sure Mark will weigh in with some more detail.

2018-11-20 11:43 UTC, currycoder commented on README.md
> +Install and configure elasticsearch as your data sources.
Could you mention that it's probably easiest to bring up a local mormont working copy following the instructions in the mormont repo [LINK]?

2018-11-20 11:43 UTC, currycoder commented on dashi/blocks.py
> +    #def __init__( self, block_id, conf ):
Can you bin the commented stuff?

2018-11-20 11:43 UTC, currycoder commented on dashi/templates/blocks/graph.html
> +        Grarff // whats the point in this? does it just show when the graph is failing to appear?
Yup, I think it's just a default.  Can you bin this? Note: Right now, `// comment` is not actually a valid HTML comment, see: https://html.com/tags/comment-tag/
In this case I would probably use django's comment template tag.

2018-11-20 11:43 UTC, currycoder commented on dashi/templates/blocks/graph.html
> +                            // CLEANER? STRING INTERPOLATION?
Bin this comment.

2018-11-20 11:43 UTC, currycoder commented on dashi/templates/blocks/graph.html
> +
It looks like a lot of bits have changed in here..  @mrmonkington would be good to get your eyes on this as I'm not sure where any BC breaks may occur.

2018-11-27 16:31 UTC, mrmonkington requested changes

2018-11-27 16:31 UTC, mrmonkington commented on README.md
> +
move all the GN specific stuff into lasagne

2018-11-27 16:31 UTC, mrmonkington commented on dashi/templates/blocks/graph.html
> +                        duration: 1000,
if the update is once per second, the thing will refresh before it's faded in, hence previous behaviour

2018-11-27 16:31 UTC, mrmonkington commented on dashi/templates/blocks/graph.html
> +                    width: '{{ width }}' - 80,
can you explain sizing logic?

2018-11-27 16:31 UTC, mrmonkington commented on dashi/templates/blocks/graph.html
> +
the graphs used to be more sophisticated and had values and warning colours and stuff, but it looks like that hasn't worked since we switched to using ES.

if it works for current purpose I'm happy to enhance again later

2018-11-27 16:31 UTC, mrmonkington commented on dashi/templates/blocks/graph.html
> +                        for (i = - '{{range}}'; i <= 0; i+=1) {
why is this now quoted?

2018-11-27 16:31 UTC, mrmonkington commented on dashi/templates/blocks/graph.html
> +                                x: time + ('{{ update_ms }}' * i),
quotes here too need explaining

2018-11-27 16:31 UTC, mrmonkington commented on dashi/templates/blocks/scratch.html
> +                console.log("Scratch block updating")
console.log should be removed if not debugging

2018-11-27 16:31 UTC, mrmonkington commented on dashi/templates/blocks/ticker.html
> +                        $( '#b{{block_id}} .ticker' ).html( parseInt(data.value).toLocaleString('en-GB', {useGrouping: true}) ).addClass(data.status).fadeIn( 100 );
does using addClass repeatedly not result in a very long class string?

2018-11-28 15:20 UTC, johnpooch commented on dashi/templates/blocks/graph.html
> +                    width: '{{ width }}' - 80,
Was a bullshitty hack. Fixed it now.

2018-11-28 15:21 UTC, johnpooch commented on dashi/templates/blocks/graph.html
> +                        for (i = - '{{range}}'; i <= 0; i+=1) {
My understanding is that it doesn't make any difference whether its quoted or not and my text editor gets very unhappy when I dont wrap in quotes.

2018-11-28 15:22 UTC, johnpooch commented on dashi/templates/blocks/ticker.html
> +                        $( '#b{{block_id}} .ticker' ).html( parseInt(data.value).toLocaleString('en-GB', {useGrouping: true}) ).addClass(data.status).fadeIn( 100 );
addClass only adds a class if it doesn't exist

2018-11-28 15:25 UTC, thomasjthomasj commented on dashi/templates/blocks/graph.html
> +                        for (i = - '{{range}}'; i <= 0; i+=1) {
You should get a Twig or Jinja extension for sublime and set it to syntax highlight `.html` files, since that's probably gonna be an issue in the future

2021-03-22 10:10 UTC, closed without merging

2021-03-22 10:14 UTC, currycoder commented
We barely knew ye